{
 "title": "AMD GPU Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "gpu",
    "label": "GPU",
    "query": {
     "query": "label_values(amd_gpu_dev_id{instance=\"localhost:2021\"},gpu_dev_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "MCLK MHz",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amd_gpu_MCLK_MHz{gpu_MCLK=~\"$gpu\"}",
     "legendFormat": "Gpu:{{gpu_MCLK}}"
    }
   ]
  },
  {
   "title": "Power W",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amd_gpu_power_Watts{gpu_power=~\"$gpu\"}",
     "legendFormat": "Gpu:{{gpu_power}}:Power"
    },
    {
     "expr": "amd_gpu_power_cap_Watts{gpu_power_cap=~\"$gpu\"}",
     "legendFormat": "Gpu:{{gpu_power_cap}}:PowerCap"
    }
   ]
  },
  {
   "title": "Utilization %",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amd_gpu_use_percent{gpu_use_percent=~\"$gpu\"}",
     "legendFormat": "Gpu:{{gpu_use_percent}}"
    }
   ]
  },
  {
   "title": "Temperature 'C",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amd_gpu_current_temperature_Celcius{gpu_current_temperature=~\"$gpu\"}",
     "legendFormat": "Gpu:{{gpu_current_temperature}}"
    }
   ]
  },
  {
   "title": "Memory Utilization %",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amd_gpu_memory_use_percent{gpu_memory_use_percent=~\"$gpu\"}",
     "legendFormat": "Gpu:{{gpu_memory_use_percent}}"
    }
   ]
  },
  {
   "title": "SCLK MHz",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amd_gpu_SCLK_MHz{gpu_SCLK=~\"$gpu\"}",
     "legendFormat": "Gpu:{{gpu_SCLK}}"
    }
   ]
  },
  {
   "title": "GPU Power W",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "amd_gpu_power_Watts{gpu_power=~\"$gpu\"}",
     "legendFormat": "Gpu:{{gpu_power}}:Power"
    },
    {
     "expr": "amd_gpu_power_cap_Watts{gpu_power_cap=~\"$gpu\"}",
     "legendFormat": "Gpu:{{gpu_power_cap}}:PowerCap"
    }
   ]
  },
  {
   "title": "GPU Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "amd_gpu_use_percent{gpu_use_percent=~\"$gpu\"}",
     "legendFormat": "Gpu:{{gpu_use_percent}}"
    }
   ]
  },
  {
   "title": "GPU Temperature 'C",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "amd_gpu_current_temperature_Celcius{gpu_current_temperature=~\"$gpu\"}",
     "legendFormat": "Gpu:{{gpu_current_temperature}}"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "amd_gpu_memory_use_percent{gpu_memory_use_percent=~\"$gpu\"}",
     "legendFormat": "Gpu:{{gpu_memory_use_percent}}"
    }
   ]
  },
  {
   "title": "GPU MCLK MHz",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "amd_gpu_MCLK_MHz{gpu_MCLK=~\"$gpu\"}",
     "legendFormat": "Gpu:{{gpu_MCLK}}"
    }
   ]
  },
  {
   "title": "GPU SCLK MHz",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "amd_gpu_SCLK_MHz{gpu_SCLK=~\"$gpu\"}",
     "legendFormat": "Gpu:{{gpu_SCLK}}"
    }
   ]
  }
 ]
}