{
 "title": "AMD CPU Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cpu",
    "label": "CPU",
    "query": {
     "query": "label_values(amd_socket_power_Watts{instance=\"localhost:2021\"},socket)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Socket Power W",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amd_socket_power_Watts{socket=~\"$cpu\"}",
     "legendFormat": "Cpu:{{socket}}:Power"
    },
    {
     "expr": "amd_power_limit_Watts{power_limit=~\"$cpu\"}",
     "legendFormat": "Cpu:{{power_limit}}:PowerCap"
    }
   ]
  },
  {
   "title": "CPU Prochot Status",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "amd_prochot_status{prochot_status=~\"$cpu\"}",
     "legendFormat": "Cpu:{{prochot_status}}"
    }
   ]
  },
  {
   "title": "CPU Socket Power W",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "amd_socket_power_Watts{socket=~\"$cpu\"}",
     "legendFormat": "Cpu:{{socket}}:Power"
    },
    {
     "expr": "amd_power_limit_Watts{power_limit=~\"$cpu\"}",
     "legendFormat": "Cpu:{{power_limit}}:PowerCap"
    }
   ]
  },
  {
   "title": "CPU Prochot Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 6 },
   "targets": [
    {
     "expr": "amd_prochot_status{prochot_status=~\"$cpu\"}",
     "legendFormat": "Cpu:{{prochot_status}}"
    }
   ]
  },
  {
   "title": "CPU Socket Energy KJ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 6 },
   "targets": [
    {
     "expr": "amd_socket_energy_KJoules{socket=~\"$cpu\"}",
     "legendFormat": "Cpu:{{socket}}"
    }
   ]
  },
  {
   "title": "CPU Core BoostLimit MHz",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 14 },
   "targets": [
    { "expr": "amd_boost_limit_Mhz", "legendFormat": "Thread:{{thread}}" }
   ]
  },
  {
   "title": "CPU Core Energy KJ",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 38 },
   "targets": [
    { "expr": "amd_core_energy", "legendFormat": "Thread:{{thread}}" }
   ]
  }
 ]
}